<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PowershellAI</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CredentialManagement" Version="1.0.2" />
        <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
        <PackageReference Include="NHotkey.Wpf" Version="4.0.0" />
    </ItemGroup>
</Project>
